#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'spider-nav','console_scripts','spider_gps_pub'
__requires__ = 'spider-nav'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('spider-nav', 'console_scripts', 'spider_gps_pub')()
    )
